<?php
/**
 * Plugin Name: Wbcom Designs - Birthday Widget for BuddyPress
 * Plugin URI: https://wbcomdesigns.com/downloads/buddypress-birthdays/
 * Description: Display upcoming birthdays
 * Version: 1.5.0
 * Author: Wbcom Designs
 * Author URI: https://wbcomdesigns.com/
 * Text Domain: buddypress-birthdays
 * Generated By: http://ensuredomains.com
 *
 * @link              https://wbcomdesigns.com/contact/
 * @since             1.0.0
 * @package           BP_Birthdays
 */

// If this file is called directly, abort.

define( 'BIRTHDAY_WIDGET_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'BIRTHDAY_WIDGET_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );


if ( ! defined( 'WPINC' ) ) {
	die;} // end if

// Let's Initialize Everything.
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
	require_once plugin_dir_path( __FILE__ ) . 'core-init.php';
}

require plugin_dir_path( __FILE__ ) . 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://demos.wbcomdesigns.com/exporter/free-plugins/buddypress-birthdays.json',
	__FILE__, // Full path to the main plugin file or functions.php.
	'buddypress-birthdays'
);
